add_newline = false
format = "$directory$git_branch $character"

[directory]
truncate_to_repo = false
truncation_length = 0
format = "[$path]($style)"

[git_branch]
symbol = ""
format = "[\\($branch\\)]($style)"
style = "purple"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
